# Generated by Django 5.2 on 2025-05-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0002_auditoriaacceso_roldescripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
