# Generated by Django 5.2 on 2025-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_LUMINOVA', '0003_alter_insumo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
